package passthrough

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const passthroughTemplate = `// Code generated by passthrough-gen. DO NOT EDIT.

package {{ .PackageName }}

{{ if .Imports }}
import (
{{- range .Imports }}
	{{ . }}
{{- end }}
)
{{ end }}

{{- range .Types }}

// {{ .Name }} mirrors {{ .SourceName }} from upstream HyperShift
type {{ .Name }} struct {
{{- range .Fields }}
	{{- if .Doc }}
	// {{ .Doc }}
	{{- end }}
	{{- range .Markers }}
	// {{ . }}
	{{- end }}
	{{ .Name }} {{ .Type }} ` + "`json:\"{{ .JSONTag }}\"`" + `
{{- end }}
}
{{- end }}
`

type templateData struct {
	PackageName string
	Imports     []string
	Types       []*TypeDef
}

// Generate creates Go source files for the passthrough types
func (g *Generator) Generate(outputDir string) error {
	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Generate TypeDef for each source type
	var typeDefs []*TypeDef
	for _, typeName := range g.SourceTypes {
		typeDef, err := g.GenerateTypeDef(typeName)
		if err != nil {
			return fmt.Errorf("generating type def for %s: %w", typeName, err)
		}
		typeDefs = append(typeDefs, typeDef)
	}

	// Collect unique imports needed
	imports := g.collectImports(typeDefs)

	// Prepare template data
	data := templateData{
		PackageName: g.OutputPackage,
		Imports:     imports,
		Types:       typeDefs,
	}

	// Execute template
	tmpl, err := template.New("passthrough").Parse(passthroughTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Write unformatted first for debugging
	outputFile := filepath.Join(outputDir, "zz_generated.passthrough.go")
	if err := os.WriteFile(outputFile+".raw", buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("writing raw output file: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w", err)
	}

	// Write to file
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	return nil
}

// collectImports extracts unique imports needed for the generated types
func (g *Generator) collectImports(typeDefs []*TypeDef) []string {
	importSet := make(map[string]bool)

	// Add source package import if we have a source package
	if g.SourcePackage != "" && g.SourcePackageAlias != "" {
		importSet[fmt.Sprintf(`%s "%s"`, g.SourcePackageAlias, g.SourcePackage)] = true
	}

	for _, typeDef := range typeDefs {
		for _, field := range typeDef.Fields {
			// Strip pointer/slice/map prefixes to get base type
			typeStr := field.Type
			typeStr = strings.TrimPrefix(typeStr, "*")
			typeStr = strings.TrimPrefix(typeStr, "[]")
			if strings.HasPrefix(typeStr, "map[") {
				// Extract value type from map[K]V
				if idx := strings.LastIndex(typeStr, "]"); idx != -1 && idx+1 < len(typeStr) {
					typeStr = typeStr[idx+1:]
				}
			}

			// Extract package from type names like "configv1.URL"
			if strings.Contains(typeStr, ".") {
				// For now, we'll need to manually map these
				// In a real implementation, we'd track imports from the AST
				if strings.HasPrefix(typeStr, "configv1.") {
					importSet[`configv1 "github.com/openshift/api/config/v1"`] = true
				}
				if strings.HasPrefix(typeStr, "corev1.") {
					importSet[`corev1 "k8s.io/api/core/v1"`] = true
				}
				if strings.HasPrefix(typeStr, "metav1.") {
					importSet[`metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"`] = true
				}
			}
		}
	}

	// Convert set to sorted slice
	var imports []string
	for imp := range importSet {
		imports = append(imports, imp)
	}

	return imports
}
