/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// wire-gen reads +wire:* markers from Go source files and emits generated Go code.
//
// Modes:
//
//	--mode=mappings (default): emits wire_mappings_generated.go containing a
//	  FieldMapping slice derived from +wire:field markers.
//
//	--mode=wrappers: emits wire_wrappers_generated.go containing wrapper types
//	  for resources annotated with +wire:watch=disabled and/or +wire:wait.
//	  The Watch method returns ErrWatchNotSupported; WaitUntil provides
//	  polling-based synchronization via a caller-supplied condition function.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

var (
	wireMarkerRE    = regexp.MustCompile(`\+wire:field=([^,\s]+),meta=([^\s]+)`)
	watchDisabledRE = regexp.MustCompile(`\+wire:watch=disabled`)
	waitRE          = regexp.MustCompile(`\+wire:wait\b`)
	nonNamespacedRE = regexp.MustCompile(`\+genclient:nonNamespaced\b`)
)

// fieldMapping holds a single wire→metadata field translation.
type fieldMapping struct {
	Wire string
	Meta string
}

// resourceType describes a CRD type annotated with +wire:watch or +wire:wait.
type resourceType struct {
	Name          string // e.g. "Cluster"
	PluralName    string // e.g. "Clusters"
	LowerName     string // e.g. "cluster"
	WatchDisabled bool
	Wait          bool
	NonNamespaced bool // set when +genclient:nonNamespaced is present
}

// ── Templates ────────────────────────────────────────────────────────────────

const mappingsTmpl = `// Code generated by wire-gen. DO NOT EDIT.

package {{.Package}}

// defaultMappings maps platform-api wire-format field names to Kubernetes
// metadata field names. Generated from +wire:field markers on CRD types.
var defaultMappings = []FieldMapping{
{{- range .Mappings}}
	{Wire: "{{.Wire}}", Meta: "{{.Meta}}"},
{{- end}}
}
`

const wrappersTmpl = `// Code generated by wire-gen. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"strconv"
{{if .AnyWait}}	"time"
{{end}}
{{if .AnyWait}}	k8serrors "k8s.io/apimachinery/pkg/api/errors"
{{end}}	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/rest"

	internalversion "{{.TypedPkgImport}}"
	v1alpha1 "{{.ApiPkgImport}}"
)
{{range .Types}}
// {{.Name}}Interface is the platform-scoped client for {{.Name}} resources.
// Only operations and options supported by the Hyperfleet platform API are exposed.
// Watch is intentionally absent — the platform API does not support the Kubernetes
// watch stream protocol; use WaitUntil for polling-based synchronization instead.
type {{.Name}}Interface interface {
	Create(ctx context.Context, obj *v1alpha1.{{.Name}}, opts CreateOptions) (*v1alpha1.{{.Name}}, error)
	Update(ctx context.Context, obj *v1alpha1.{{.Name}}, opts UpdateOptions) (*v1alpha1.{{.Name}}, error)
	Delete(ctx context.Context, name string, opts DeleteOptions) error
	Get(ctx context.Context, name string, opts GetOptions) (*v1alpha1.{{.Name}}, error)
	List(ctx context.Context, opts ListOptions) (*v1alpha1.{{.Name}}List, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts PatchOptions) (*v1alpha1.{{.Name}}, error)
{{- if .Wait}}
	// WaitUntil polls until condition(obj) returns true, the resource is absent
	// (condition is called with nil), or the timeout elapses.
	WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.{{.Name}}) bool, interval, timeout time.Duration) error
{{- end}}
}

type {{.LowerName}}Client struct {
	inner internalversion.{{.Name}}Interface
}

func (c *{{.LowerName}}Client) Create(ctx context.Context, obj *v1alpha1.{{.Name}}, opts CreateOptions) (*v1alpha1.{{.Name}}, error) {
	return c.inner.Create(ctx, obj, metav1.CreateOptions{})
}

func (c *{{.LowerName}}Client) Get(ctx context.Context, name string, opts GetOptions) (*v1alpha1.{{.Name}}, error) {
	return c.inner.Get(ctx, name, metav1.GetOptions{})
}

func (c *{{.LowerName}}Client) List(ctx context.Context, opts ListOptions) (*v1alpha1.{{.Name}}List, error) {
	if opts.Limit < 0 || opts.Limit > 100 {
		return nil, fmt.Errorf("List: Limit must be between 0 and 100, got %d", opts.Limit)
	}
	if opts.Offset < 0 {
		return nil, fmt.Errorf("List: Offset must be non-negative, got %d", opts.Offset)
	}
	mo := metav1.ListOptions{Limit: opts.Limit}
	if opts.Offset > 0 {
		mo.Continue = strconv.FormatInt(opts.Offset, 10)
	}
	return c.inner.List(ctx, mo)
}

func (c *{{.LowerName}}Client) Update(ctx context.Context, obj *v1alpha1.{{.Name}}, opts UpdateOptions) (*v1alpha1.{{.Name}}, error) {
	// The generated client builds the PUT URL using obj.Name (the human-readable
	// name), but the platform API routes mutations by UID. Setting Name to the
	// UID on a deep copy ensures the URL is correct without mutating the caller's
	// object. The name field sent in the request body is ignored by the server —
	// the update DTO only binds "spec", so the JSON decoder discards everything
	// else, including any name/id fields.
	routed := obj.DeepCopy()
	routed.Name = string(obj.UID)
	return c.inner.Update(ctx, routed, metav1.UpdateOptions{})
}

func (c *{{.LowerName}}Client) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts PatchOptions) (*v1alpha1.{{.Name}}, error) {
	return c.inner.Patch(ctx, name, pt, data, metav1.PatchOptions{})
}

func (c *{{.LowerName}}Client) Delete(ctx context.Context, name string, opts DeleteOptions) error {
	return c.inner.Delete(ctx, name, metav1.DeleteOptions{})
}
{{if .Wait}}
func (c *{{.LowerName}}Client) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.{{.Name}}) bool, interval, timeout time.Duration) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	poll := func() (bool, error) {
		obj, err := c.inner.Get(ctx, id, metav1.GetOptions{})
		if err != nil {
			if k8serrors.IsNotFound(err) {
				return condition(nil), nil
			}
			// Transient server-side errors are retried; only client errors are fatal.
			if k8serrors.IsServiceUnavailable(err) || k8serrors.IsServerTimeout(err) || k8serrors.IsInternalError(err) {
				return false, nil
			}
			return false, err
		}
		return condition(obj), nil
	}
	if interval <= 0 {
		return fmt.Errorf("WaitUntil: interval must be positive, got %v", interval)
	}
	if done, err := poll(); err != nil || done {
		return err
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			if done, err := poll(); err != nil || done {
				return err
			}
		}
	}
}
{{- end}}
{{end -}}
// V1alpha1Interface is the platform-scoped typed client for the hyperfleet.io/v1alpha1 group.
type V1alpha1Interface interface {
	RESTClient() rest.Interface
{{- range .Types}}
{{- if .NonNamespaced}}
	{{.PluralName}}() {{.Name}}Interface
{{- else}}
	{{.PluralName}}(namespace string) {{.Name}}Interface
{{- end}}
{{- end}}
}

type wrappedV1alpha1 struct {
	inner internalversion.V1alpha1Interface
}

// NewV1alpha1Client wraps the generated typed client with platform-specific interfaces.
func NewV1alpha1Client(inner internalversion.V1alpha1Interface) V1alpha1Interface {
	return &wrappedV1alpha1{inner: inner}
}

func (w *wrappedV1alpha1) RESTClient() rest.Interface {
	return w.inner.RESTClient()
}
{{range .Types}}
{{- if .NonNamespaced}}
func (w *wrappedV1alpha1) {{.PluralName}}() {{.Name}}Interface {
	return &{{.LowerName}}Client{inner: w.inner.{{.PluralName}}()}
}
{{- else}}
func (w *wrappedV1alpha1) {{.PluralName}}(namespace string) {{.Name}}Interface {
	return &{{.LowerName}}Client{inner: w.inner.{{.PluralName}}(namespace)}
}
{{- end}}
{{end}}`

// ── main ─────────────────────────────────────────────────────────────────────

func main() {
	mode := flag.String("mode", "mappings", "generation mode: mappings or wrappers")
	inputDir := flag.String("input-dir", "", "directory of Go source files to scan for +wire:* markers")
	outputDir := flag.String("output-dir", "", "directory to write the generated file")
	outputPkg := flag.String("output-pkg", "transport", "Go package name for the generated file")
	headerFile := flag.String("go-header-file", "", "file whose contents are prepended to the generated output")
	typedPkg := flag.String("typed-pkg-import", "", "[wrappers] import path of the generated typed client package")
	apiPkg := flag.String("api-pkg-import", "", "[wrappers] import path of the CRD API types package")
	flag.Parse()

	if *inputDir == "" || *outputDir == "" {
		fmt.Fprintln(os.Stderr, "wire-gen: --input-dir and --output-dir are required")
		os.Exit(1)
	}

	header := readHeader(*headerFile)

	if err := os.MkdirAll(*outputDir, 0o755); err != nil {
		fatalf("creating output dir: %v", err)
	}

	switch *mode {
	case "mappings":
		generateMappings(*inputDir, *outputDir, *outputPkg, header)
	case "wrappers":
		if *typedPkg == "" || *apiPkg == "" {
			fmt.Fprintln(os.Stderr, "wire-gen: wrappers mode requires --typed-pkg-import and --api-pkg-import")
			os.Exit(1)
		}
		generateWrappers(*inputDir, *outputDir, *outputPkg, *typedPkg, *apiPkg, header)
	default:
		fatalf("unknown mode %q; use mappings or wrappers", *mode)
	}
}

// ── mappings mode ─────────────────────────────────────────────────────────────

func generateMappings(inputDir, outputDir, pkg, header string) {
	mappings := collectMappings(inputDir)

	outPath := filepath.Join(outputDir, "wire_mappings_generated.go")
	f, err := os.Create(outPath)
	if err != nil {
		fatalf("creating %s: %v", outPath, err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fatalf("closing %s: %v", outPath, err)
		}
		fmt.Printf("wire-gen: wrote %s\n", outPath)
	}()

	if _, err := fmt.Fprint(f, header); err != nil {
		fatalf("writing header to %s: %v", outPath, err)
	}

	tmpl := template.Must(template.New("mappings").Parse(mappingsTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package":  pkg,
		"Mappings": mappings,
	}); err != nil {
		fatalf("rendering template: %v", err)
	}
}

// collectMappings parses all Go source files in dir and extracts unique
// +wire:field=<wire>,meta=<meta> markers from any comment in the file.
// All comment groups are scanned so markers in floating comment blocks are captured.
func collectMappings(dir string) []fieldMapping {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		fatalf("parsing %s: %v", dir, err)
	}

	seen := map[string]bool{}
	var mappings []fieldMapping

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, cg := range file.Comments {
				for _, comment := range cg.List {
					for _, m := range wireMarkerRE.FindAllStringSubmatch(comment.Text, -1) {
						key := m[1] + ":" + m[2]
						if !seen[key] {
							seen[key] = true
							mappings = append(mappings, fieldMapping{Wire: m[1], Meta: m[2]})
						}
					}
				}
			}
		}
	}

	sort.Slice(mappings, func(i, j int) bool { return mappings[i].Wire < mappings[j].Wire })
	return mappings
}

// ── wrappers mode ─────────────────────────────────────────────────────────────

func generateWrappers(inputDir, outputDir, pkg, typedPkgImport, apiPkgImport, header string) {
	types := collectResourceTypes(inputDir)
	if len(types) == 0 {
		fatalf("no resource types with +wire:watch or +wire:wait markers found in %s", inputDir)
	}

	outPath := filepath.Join(outputDir, "wire_wrappers_generated.go")
	f, err := os.Create(outPath)
	if err != nil {
		fatalf("creating %s: %v", outPath, err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fatalf("closing %s: %v", outPath, err)
		}
		fmt.Printf("wire-gen: wrote %s\n", outPath)
	}()

	if _, err := fmt.Fprint(f, header); err != nil {
		fatalf("writing header to %s: %v", outPath, err)
	}

	anyWait, anyWatchDisabled := false, false
	for _, t := range types {
		if t.Wait {
			anyWait = true
		}
		if t.WatchDisabled {
			anyWatchDisabled = true
		}
	}

	tmpl := template.Must(template.New("wrappers").Parse(wrappersTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package":          pkg,
		"ApiPkgImport":     apiPkgImport,
		"TypedPkgImport":   typedPkgImport,
		"Types":            types,
		"AnyWait":          anyWait,
		"AnyWatchDisabled": anyWatchDisabled,
	}); err != nil {
		fatalf("rendering template: %v", err)
	}
}

// collectResourceTypes scans all Go source files in dir for type declarations
// annotated with +wire:watch=disabled and/or +wire:wait.
//
// Because generators conventionally place markers in a floating comment block
// (separated by a blank line from the actual doc comment), markers are found by
// scanning all comment groups and associating each group with the nearest type
// declaration that follows it in the file.
func collectResourceTypes(dir string) []resourceType {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		fatalf("parsing %s: %v", dir, err)
	}

	seen := map[string]bool{}
	var types []resourceType

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			// Collect all type declarations with their source positions.
			type typePos struct {
				name string
				pos  token.Pos
			}
			var typeDecls []typePos
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					typeDecls = append(typeDecls, typePos{name: ts.Name.Name, pos: gd.Pos()})
				}
			}
			sort.Slice(typeDecls, func(i, j int) bool { return typeDecls[i].pos < typeDecls[j].pos })

			// For each comment group containing watch/wait markers, find the
			// next type declaration that follows it.
			for _, cg := range file.Comments {
				var hasWatch, hasWait, hasNonNamespaced bool
				for _, c := range cg.List {
					if watchDisabledRE.MatchString(c.Text) {
						hasWatch = true
					}
					if waitRE.MatchString(c.Text) {
						hasWait = true
					}
					if nonNamespacedRE.MatchString(c.Text) {
						hasNonNamespaced = true
					}
				}
				if !hasWatch && !hasWait {
					continue
				}

				cgEnd := cg.End()
				for _, td := range typeDecls {
					if td.pos <= cgEnd {
						continue
					}
					if seen[td.name] {
						continue
					}
					seen[td.name] = true
					name := td.name
					types = append(types, resourceType{
						Name:          name,
						PluralName:    name + "s",
						LowerName:     strings.ToLower(name[:1]) + name[1:],
						WatchDisabled: hasWatch,
						Wait:          hasWait,
						NonNamespaced: hasNonNamespaced,
					})
					break
				}
			}
		}
	}

	sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })
	return types
}

// ── helpers ───────────────────────────────────────────────────────────────────

func readHeader(path string) string {
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		fatalf("reading header file: %v", err)
	}
	return strings.ReplaceAll(string(b), "YEAR", strconv.Itoa(time.Now().Year()))
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "wire-gen: "+format+"\n", args...)
	os.Exit(1)
}
