// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Cluster is the Schema for the clusters API.
// It represents a ROSA HCP cluster whose lifecycle is managed by the hyperfleet-operator.
// metadata.namespace is the owning account ("account-<id>"); metadata.name is the
// client-chosen cluster name (a DNS label of at most 18 characters, never changed);
// metadata.uid is the cluster ID. On the management cluster the cluster's objects
// live in the namespace "cluster-<uid>".
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
// +genclient
// +genclient:nonNamespaced
// +bridge:watch=disabled
// +bridge:wait
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +required
	Spec ClusterSpec `json:"spec"`
	// +optional
	Status ClusterStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}
