// Package public provides defaulting helpers for HyperFleet public API types.
//
// These defaults mirror the server-side defaults applied by the hyperfleet-operator
// and are provided for client-side convenience (e.g., validation, UI pre-population).
// The server always applies its own defaults, so these functions are optional.
//
// Default values are extracted from +kubebuilder:default markers in the API types
// and code-generated by default-gen. See zz_generated.defaults.go for the generated code.
package public

import (
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	"github.com/openshift/hypershift/api/util/ipnet"
)

// Re-export generated constants for backwards compatibility
const (
	// DefaultClusterNetworkCIDR is the default CIDR for pod networking
	DefaultClusterNetworkCIDR = DefaultClusterNetworkingClusterNetworkCIDR

	// DefaultServiceNetworkCIDR is the default CIDR for service networking
	DefaultServiceNetworkCIDR = DefaultClusterNetworkingServiceNetworkCIDR

	// DefaultMachineNetworkCIDR is the default CIDR for machine networking
	DefaultMachineNetworkCIDR = DefaultClusterNetworkingMachineNetworkCIDR

	// DefaultNetworkType is the default SDN provider
	DefaultNetworkType = hypershiftv1beta1.NetworkType(DefaultClusterNetworkingNetworkType)
)

// SetNetworkingDefaults applies default values to ClusterNetworking if not already set.
// This is a client-side helper that mirrors the server-side defaults applied by the operator.
//
// This wraps the generated SetClusterNetworkingDefaults to work with hypershiftv1beta1.ClusterNetworking.
func SetNetworkingDefaults(networking *hypershiftv1beta1.ClusterNetworking) {
	if networking == nil {
		return
	}

	// Set default NetworkType if not specified
	if networking.NetworkType == "" {
		networking.NetworkType = DefaultNetworkType
	}

	// Set default ClusterNetwork (pod CIDR) if not specified
	if len(networking.ClusterNetwork) == 0 {
		networking.ClusterNetwork = []hypershiftv1beta1.ClusterNetworkEntry{
			{CIDR: mustParseCIDR(DefaultClusterNetworkCIDR)},
		}
	}

	// Set default ServiceNetwork if not specified
	if len(networking.ServiceNetwork) == 0 {
		networking.ServiceNetwork = []hypershiftv1beta1.ServiceNetworkEntry{
			{CIDR: mustParseCIDR(DefaultServiceNetworkCIDR)},
		}
	}

	// Set default MachineNetwork if not specified
	if len(networking.MachineNetwork) == 0 {
		networking.MachineNetwork = []hypershiftv1beta1.MachineNetworkEntry{
			{CIDR: mustParseCIDR(DefaultMachineNetworkCIDR)},
		}
	}
}

// SetHostedClusterSpecDefaults applies default values to HostedClusterSpecPassthrough.
// Currently only sets networking defaults, but can be extended for other fields.
func SetHostedClusterSpecDefaults(spec *HostedClusterSpecPassthrough) {
	if spec == nil {
		return
	}

	SetNetworkingDefaults(&spec.Networking)
}

// mustParseCIDR parses a CIDR string and panics on error.
// This is safe for constant default values that are known to be valid.
func mustParseCIDR(cidr string) ipnet.IPNet {
	parsed, err := ipnet.ParseCIDR(cidr)
	if err != nil {
		panic("invalid default CIDR: " + cidr + ": " + err.Error())
	}
	return *parsed
}
