// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DNSReservationStatus describes the operator-allocated DNS name.
type DNSReservationStatus struct {
	// Conditions represent the latest observations of the reservation's state.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// Phase summarizes allocation state. BaseDomain is empty unless Phase is Ready.
	// +optional
	Phase DNSReservationPhase `json:"phase,omitempty"`
	// BaseDomain is the assigned domain, e.g. "f7a3.0.openshiftapps.com".
	// It is populated when Phase is Ready.
	// +optional
	BaseDomain string `json:"baseDomain,omitempty"`
	// ObservedGeneration is the most recent generation observed by the controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}
