// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DNSReservation reserves a DNS prefix within a specific zone shard.
// Customers create it in their account namespace (account-<accountID>). The
// regional DNS zone and allocated prefix are operator-managed; the assigned base
// domain is reported in status. metadata.name is customer-selected.
// Labels:
//   - hyperfleet.io/account-id: AWS account that owns this reservation (always set).
//   - hyperfleet.io/claimed-by-cluster-uid: set when a Cluster claims the reservation.
//
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
// +genclient
// +genclient:nonNamespaced
// +resourceName=dns_reservations
// +bridge:watch=disabled
// +bridge:wait
type DNSReservation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// Spec is empty; customers provide their reservation name in metadata.
	// +optional
	Spec DNSReservationSpec `json:"spec,omitempty"`
	// Status describes whether the reservation has been allocated and its base domain.
	// +optional
	Status DNSReservationStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true
type DNSReservationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSReservation `json:"items"`
}
