// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NodePool is the Schema for the nodepools API.
// It represents a set of worker nodes for a Cluster.
// It lives in its cluster's account namespace, is named "<cluster>.<nodepool>",
// and points at the cluster through a controller ownerReference and the
// hyperfleet.io/cluster-uid label.
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
// +genclient
// +bridge:watch=disabled
// +bridge:wait
type NodePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +required
	Spec NodePoolSpec `json:"spec"`
	// +optional
	Status NodePoolStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true
type NodePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NodePool `json:"items"`
}
