// Code generated by conversion-gen. DO NOT EDIT.

package public

// NodePoolSpec defines the desired state of a NodePool.
// metadata.name is "<cluster>.<nodepool>". The parent Cluster is identified by the
// controller ownerReference and the hyperfleet.io/cluster-uid label, both set at create.
type NodePoolSpec struct {
	// DisplayName is a human-readable name for the node pool.
	// +hyperfleet:write-mode=mutable
	// +kubebuilder:validation:MaxLength=256
	// +optional
	DisplayName string `json:"displayName,omitempty"`
	// AutoRepair controls whether unhealthy nodes are automatically replaced.
	// +hyperfleet:write-mode=mutable
	// +optional
	AutoRepair *bool `json:"autoRepair,omitempty"`
	// Labels are customer-defined labels applied to nodes in this pool.
	// +hyperfleet:write-mode=mutable
	// +kubebuilder:validation:MaxProperties=100
	// +optional
	Labels map[string]string `json:"labels,omitempty"`
	// NodePool contains the upstream HyperShift fields, mirrored as
	// passthrough types with per-field visibility and write-mode markers.
	// +kubebuilder:validation:Required
	NodePool NodePoolSpecPassthrough `json:"nodePool"`
}
