// Code generated by conversion-gen. DO NOT EDIT.

package public

// OidcConfigSpec defines the desired state of an OidcConfig.
// +kubebuilder:validation:XValidation:rule="self.secretArn == oldSelf.secretArn",message="spec.secretArn is immutable"
// +kubebuilder:validation:XValidation:rule="self.installerRoleArn == oldSelf.installerRoleArn",message="spec.installerRoleArn is immutable"
// +kubebuilder:validation:XValidation:rule="self.issuerUrl == oldSelf.issuerUrl",message="spec.issuerUrl is immutable"
type OidcConfigSpec struct {
	// IssuerUrl is the OIDC issuer URL, hosted by the customer.
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:Required
	IssuerUrl string `json:"issuerUrl"`
	// SecretArn is the ARN of the customer's Secrets Manager secret containing the RSA private key.
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^arn:aws:secretsmanager:.*$`
	SecretArn string `json:"secretArn"`
	// InstallerRoleArn is the ARN of the cross-account IAM role used to read the customer's secret.
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^arn:aws:iam::.*$`
	InstallerRoleArn string `json:"installerRoleArn"`
}
