// Code generated by conversion-gen. DO NOT EDIT.

package public

// OidcConfigSpec defines the desired state of an OidcConfig.
// +kubebuilder:validation:XValidation:rule="self.type != 'managed' || ((!has(self.secretArn) || size(self.secretArn) == 0) && (!has(self.installerRoleArn) || size(self.installerRoleArn) == 0))",message="managed type must not set secretArn or installerRoleArn"
// +kubebuilder:validation:XValidation:rule="self.type != 'unmanaged' || (size(self.secretArn) > 0 && size(self.installerRoleArn) > 0)",message="unmanaged type requires secretArn and installerRoleArn"
// +kubebuilder:validation:XValidation:rule="self.type == oldSelf.type",message="spec.type is immutable"
// +kubebuilder:validation:XValidation:rule="has(self.secretArn) == has(oldSelf.secretArn) && (!has(self.secretArn) || self.secretArn == oldSelf.secretArn)",message="spec.secretArn is immutable"
// +kubebuilder:validation:XValidation:rule="has(self.installerRoleArn) == has(oldSelf.installerRoleArn) && (!has(self.installerRoleArn) || self.installerRoleArn == oldSelf.installerRoleArn)",message="spec.installerRoleArn is immutable"
// +kubebuilder:validation:XValidation:rule="self.issuerUrl == oldSelf.issuerUrl",message="spec.issuerUrl is immutable"
type OidcConfigSpec struct {
	// Type is the OIDC configuration mode.
	// +kubebuilder:validation:Enum=managed;unmanaged
	// +hyperfleet:write-mode=immutable
	Type string `json:"type"`
	// IssuerUrl is the OIDC issuer URL.
	// Required for both types; computed by platform-api for managed configs,
	// customer-supplied for unmanaged configs.
	// +hyperfleet:write-mode=immutable
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	IssuerUrl string `json:"issuerUrl"`
	// SecretArn is the ARN of the customer's Secrets Manager secret containing the RSA private key.
	// Required for unmanaged configs; must be empty for managed configs.
	// +hyperfleet:write-mode=immutable
	// +optional
	// +kubebuilder:validation:Pattern=`^(arn:aws:secretsmanager:.*)?$`
	SecretArn string `json:"secretArn"`
	// InstallerRoleArn is the ARN of the cross-account IAM role used to read the customer's secret.
	// Required for unmanaged configs; must be empty for managed configs.
	// +hyperfleet:write-mode=immutable
	// +optional
	// +kubebuilder:validation:Pattern=`^(arn:aws:iam::.*)?$`
	InstallerRoleArn string `json:"installerRoleArn"`
}
