// Code generated by conversion-gen. DO NOT EDIT.

package public

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OidcConfig is the Schema for the oidcconfigs API.
// It represents a reusable OIDC configuration for cluster identity.
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
type OidcConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +required
	Spec OidcConfigSpec `json:"spec"`
	// +optional
	Status OidcConfigStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true
type OidcConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OidcConfig `json:"items"`
}
