// Code generated by default-gen. DO NOT EDIT.
//
// This file contains constant default values extracted from +kubebuilder:default markers.
// The SetDefaults functions are defined in defaults.go (manually maintained).

package public

// Default values extracted from +kubebuilder:default markers
const (
	// DefaultClusterNetworkingNetworkType is the default value for ClusterNetworking.NetworkType
	DefaultClusterNetworkingNetworkType = "OVNKubernetes"
)

// Default CIDR strings extracted from +kubebuilder:default markers
const (
	// DefaultClusterNetworkingMachineNetworkCIDR is the default CIDR for ClusterNetworking.MachineNetwork
	DefaultClusterNetworkingMachineNetworkCIDR = "10.0.0.0/16"
	// DefaultClusterNetworkingClusterNetworkCIDR is the default CIDR for ClusterNetworking.ClusterNetwork
	DefaultClusterNetworkingClusterNetworkCIDR = "10.132.0.0/14"
	// DefaultClusterNetworkingServiceNetworkCIDR is the default CIDR for ClusterNetworking.ServiceNetwork
	DefaultClusterNetworkingServiceNetworkCIDR = "172.31.0.0/16"
)
