package markers

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"
)

const registryTemplate = `// Code generated by marker-scanner. DO NOT EDIT.

package registry

import (
	"github.com/openshift-online/rosa-hyperfleet-api/hack/api-codegen/pkg/markers"
)

// Type aliases re-exported from markers so that consumers of this package
// do not need to import markers directly.
type WriteMode = markers.WriteMode
type FieldMeta = markers.FieldMeta
type FeatureGateWriteMode = markers.FeatureGateWriteMode
type TypedFieldRegistry = markers.TypedFieldRegistry

const (
	Mutable    = markers.Mutable
	Immutable  = markers.Immutable
	ServiceSet = markers.ServiceSet
)

// FieldRegistry is a per-CRD-type field registry that allows different validation rules
// for the same field path in different resource types (e.g., Cluster vs NodePool)
var FieldRegistry = TypedFieldRegistry{
{{- range $owner := .SortedOwners }}
	"{{ $owner }}": {
		{{- range $field := index $.ByOwner $owner }}
		"{{ $field.FieldPath }}": {
			FieldPath: "{{ $field.FieldPath }}",
			{{- if $field.UpdateAction }}
			UpdateAction: "{{ $field.UpdateAction }}",
			{{- end }}
			{{- if $field.WriteMode }}
			WriteMode: {{ $field.WriteMode }},
			{{- end }}
			{{- if $field.FeatureGate }}
			FeatureGate: "{{ $field.FeatureGate }}",
			{{- end }}
			{{- if $field.Hidden }}
			Hidden: true,
			{{- end }}
			{{- if $field.IsReducedContainer }}
			IsReducedContainer: true,
			{{- end }}
			{{- if $field.GatedWriteModes }}
			FeatureGateAwareWriteModes: []FeatureGateWriteMode{
				{{- range $gated := $field.GatedWriteModes }}
				{FeatureGate: "{{ $gated.FeatureGate }}", WriteMode: {{ $gated.WriteMode }}},
				{{- end }}
			},
			{{- end }}
			OwnerType: "{{ $field.OwnerType }}",
			OwnerGVK: "{{ $field.OwnerGVK }}",
		},
		{{- end }}
	},
{{- end }}
}
`

type templateData struct {
	ByOwner      map[string][]templateField
	SortedOwners []string
}

type templateField struct {
	UpdateAction       string
	FieldPath          string
	WriteMode          string
	FeatureGate        string
	Hidden             bool
	IsReducedContainer bool
	GatedWriteModes    []templateGatedWriteMode
	OwnerType          string
	OwnerGVK           string
}

type templateGatedWriteMode struct {
	FeatureGate string
	WriteMode   string
}

// Generate creates the registry Go file from collected metadata
func (s *MarkerScanner) Generate(outputFile string) error {
	// Ensure output directory exists
	dir := filepath.Dir(outputFile)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Prepare template data
	data := templateData{
		ByOwner: make(map[string][]templateField),
	}

	// Collect all owner types
	var owners []string
	for owner := range s.TypedRegistry {
		owners = append(owners, owner)
	}
	sort.Strings(owners)

	// Process each owner type and its fields
	for _, owner := range owners {
		fields := s.TypedRegistry[owner]

		// Collect and sort field paths for this owner
		var paths []string
		for path := range fields {
			paths = append(paths, path)
		}
		sort.Strings(paths)

		// Process each field
		for _, path := range paths {
			meta := fields[path]
			field := templateField{
				UpdateAction:       meta.UpdateAction,
				FieldPath:          meta.FieldPath,
				FeatureGate:        meta.FeatureGate,
				Hidden:             meta.Hidden,
				IsReducedContainer: meta.IsReducedContainer,
				OwnerType:          meta.OwnerType,
				OwnerGVK:           meta.OwnerGVK,
			}

			// Convert WriteMode to const reference
			switch meta.WriteMode {
			case Mutable:
				field.WriteMode = "Mutable"
			case Immutable:
				field.WriteMode = "Immutable"
			case ServiceSet:
				field.WriteMode = "ServiceSet"
			}

			// Convert FeatureGateAwareWriteModes
			for _, gated := range meta.FeatureGateAwareWriteModes {
				var writeModeStr string
				switch gated.WriteMode {
				case Mutable:
					writeModeStr = "Mutable"
				case Immutable:
					writeModeStr = "Immutable"
				case ServiceSet:
					writeModeStr = "ServiceSet"
				}
				field.GatedWriteModes = append(field.GatedWriteModes, templateGatedWriteMode{
					FeatureGate: gated.FeatureGate,
					WriteMode:   writeModeStr,
				})
			}

			// Populate ByOwner map for typed registry
			data.ByOwner[owner] = append(data.ByOwner[owner], field)
		}
	}

	// Generate synthetic full paths for upstream-reduced types embedded in CRDs
	s.generateSyntheticPaths(data.ByOwner)

	// Update TypedRegistry with synthetic paths so they're included in JSON output
	s.updateRegistryWithSyntheticPaths(data.ByOwner)

	// Overlay actions only after discovery and synthetic expansion, preserving restrictions.
	if err := s.applyUpdateActions(); err != nil {
		return err
	}
	for owner, fields := range data.ByOwner {
		for i := range fields {
			fields[i].UpdateAction = s.TypedRegistry[owner][fields[i].FieldPath].UpdateAction
		}
	}

	// Set sorted owners for template
	data.SortedOwners = owners

	// Execute template
	tmpl, err := template.New("registry").Parse(registryTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w", err)
	}

	// Write to file
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	return nil
}
