package markers

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"text/template"
)

const registryTemplate = `// Code generated by marker-scanner. DO NOT EDIT.

package registry

// WriteMode defines how a field can be mutated by customers
type WriteMode string

const (
	// Mutable fields can be set on create and changed on update
	Mutable WriteMode = "mutable"

	// Immutable fields can be set on create but cannot be changed on update
	Immutable WriteMode = "immutable"

	// ServiceSet fields are set by the platform and cannot be set by customers
	ServiceSet WriteMode = "service-set"
)

// FeatureGateWriteMode represents a write-mode override for a specific feature gate
type FeatureGateWriteMode struct {
	// FeatureGate is the gate that enables this write-mode (empty string = default/no gates enabled)
	FeatureGate string

	// WriteMode is the effective write-mode when this gate condition matches
	WriteMode WriteMode
}

// FieldMeta contains metadata for a single field
type FieldMeta struct {
	// FieldPath is the JSON path to the field (e.g., "spec.name")
	FieldPath string

	// WriteMode controls customer mutability
	WriteMode WriteMode

	// FeatureGate is the gate required to use this field (empty if no gate required)
	FeatureGate string

	// Hidden indicates if the field is excluded from OpenAPI
	Hidden bool

	// FeatureGateAwareWriteModes allows write-mode to vary based on enabled feature gates
	FeatureGateAwareWriteModes []FeatureGateWriteMode
}

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{
{{- range .Fields }}
	"{{ .FieldPath }}": {
		FieldPath: "{{ .FieldPath }}",
		{{- if .WriteMode }}
		WriteMode: {{ .WriteMode }},
		{{- end }}
		{{- if .FeatureGate }}
		FeatureGate: "{{ .FeatureGate }}",
		{{- end }}
		{{- if .Hidden }}
		Hidden: true,
		{{- end }}
		{{- if .GatedWriteModes }}
		FeatureGateAwareWriteModes: []FeatureGateWriteMode{
			{{- range .GatedWriteModes }}
			{FeatureGate: "{{ .FeatureGate }}", WriteMode: {{ .WriteMode }}},
			{{- end }}
		},
		{{- end }}
	},
{{- end }}
}
`

type templateData struct {
	Fields []templateField
}

type templateField struct {
	FieldPath       string
	WriteMode       string
	FeatureGate     string
	Hidden          bool
	GatedWriteModes []templateGatedWriteMode
}

type templateGatedWriteMode struct {
	FeatureGate string
	WriteMode   string
}

// Generate creates the registry Go file from collected metadata
func (s *MarkerScanner) Generate(outputFile string) error {
	// Ensure output directory exists
	dir := filepath.Dir(outputFile)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	// Prepare template data
	data := templateData{
		Fields: make([]templateField, 0, len(s.Registry)),
	}

	// Sort fields for deterministic output
	var paths []string
	for path := range s.Registry {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		meta := s.Registry[path]
		field := templateField{
			FieldPath:   meta.FieldPath,
			FeatureGate: meta.FeatureGate,
			Hidden:      meta.Hidden,
		}

		// Convert WriteMode to const reference
		switch meta.WriteMode {
		case Mutable:
			field.WriteMode = "Mutable"
		case Immutable:
			field.WriteMode = "Immutable"
		case ServiceSet:
			field.WriteMode = "ServiceSet"
		}

		// Convert FeatureGateAwareWriteModes
		for _, gated := range meta.FeatureGateAwareWriteModes {
			var writeModeStr string
			switch gated.WriteMode {
			case Mutable:
				writeModeStr = "Mutable"
			case Immutable:
				writeModeStr = "Immutable"
			case ServiceSet:
				writeModeStr = "ServiceSet"
			}
			field.GatedWriteModes = append(field.GatedWriteModes, templateGatedWriteMode{
				FeatureGate: gated.FeatureGate,
				WriteMode:   writeModeStr,
			})
		}

		data.Fields = append(data.Fields, field)
	}

	// Execute template
	tmpl, err := template.New("registry").Parse(registryTemplate)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w", err)
	}

	// Write to file
	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	return nil
}
