// Code generated by marker-scanner. DO NOT EDIT.

package registry

import (
	"github.com/openshift-online/rosa-hyperfleet-api/hack/api-codegen/pkg/markers"
)

// Type aliases re-exported from markers so that consumers of this package
// do not need to import markers directly.
type WriteMode = markers.WriteMode
type FieldMeta = markers.FieldMeta
type FeatureGateWriteMode = markers.FeatureGateWriteMode

const (
	Mutable    = markers.Mutable
	Immutable  = markers.Immutable
	ServiceSet = markers.ServiceSet
)

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{
	"allowedUnsafeSysctls": {
		FieldPath: "allowedUnsafeSysctls",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"apiServer": {
		FieldPath: "apiServer",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"authentication": {
		FieldPath: "authentication",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"containerLogMaxFiles": {
		FieldPath: "containerLogMaxFiles",
		WriteMode: Mutable,
	},
	"containerLogMaxSize": {
		FieldPath: "containerLogMaxSize",
		WriteMode: Mutable,
	},
	"cpuManagerPolicy": {
		FieldPath: "cpuManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"cpuManagerPolicyOptions": {
		FieldPath: "cpuManagerPolicyOptions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"cpuManagerReconcilePeriod": {
		FieldPath: "cpuManagerReconcilePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionHard": {
		FieldPath: "evictionHard",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionSoft": {
		FieldPath: "evictionSoft",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionSoftGracePeriod": {
		FieldPath: "evictionSoftGracePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"featureGate": {
		FieldPath: "featureGate",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"image": {
		FieldPath: "image",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"imageGCHighThresholdPercent": {
		FieldPath: "imageGCHighThresholdPercent",
		WriteMode: Mutable,
	},
	"imageGCLowThresholdPercent": {
		FieldPath: "imageGCLowThresholdPercent",
		WriteMode: Mutable,
	},
	"imageMinimumGCAge": {
		FieldPath: "imageMinimumGCAge",
		WriteMode: Mutable,
	},
	"ingress": {
		FieldPath: "ingress",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubeReserved": {
		FieldPath: "kubeReserved",
		WriteMode: Immutable,
	},
	"kubelet": {
		FieldPath: "kubelet",
		WriteMode: ServiceSet,
	},
	"kubelet.allowedUnsafeSysctls": {
		FieldPath: "kubelet.allowedUnsafeSysctls",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.containerLogMaxFiles": {
		FieldPath: "kubelet.containerLogMaxFiles",
		WriteMode: Mutable,
	},
	"kubelet.containerLogMaxSize": {
		FieldPath: "kubelet.containerLogMaxSize",
		WriteMode: Mutable,
	},
	"kubelet.cpuManagerPolicy": {
		FieldPath: "kubelet.cpuManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.cpuManagerPolicyOptions": {
		FieldPath: "kubelet.cpuManagerPolicyOptions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.cpuManagerReconcilePeriod": {
		FieldPath: "kubelet.cpuManagerReconcilePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionHard": {
		FieldPath: "kubelet.evictionHard",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionSoft": {
		FieldPath: "kubelet.evictionSoft",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionSoftGracePeriod": {
		FieldPath: "kubelet.evictionSoftGracePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.imageGCHighThresholdPercent": {
		FieldPath: "kubelet.imageGCHighThresholdPercent",
		WriteMode: Mutable,
	},
	"kubelet.imageGCLowThresholdPercent": {
		FieldPath: "kubelet.imageGCLowThresholdPercent",
		WriteMode: Mutable,
	},
	"kubelet.imageMinimumGCAge": {
		FieldPath: "kubelet.imageMinimumGCAge",
		WriteMode: Mutable,
	},
	"kubelet.kubeReserved": {
		FieldPath: "kubelet.kubeReserved",
		WriteMode: Immutable,
	},
	"kubelet.maxPods": {
		FieldPath: "kubelet.maxPods",
		WriteMode: Mutable,
	},
	"kubelet.memoryThrottlingFactor": {
		FieldPath: "kubelet.memoryThrottlingFactor",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.podPidsLimit": {
		FieldPath: "kubelet.podPidsLimit",
		WriteMode: Mutable,
	},
	"kubelet.registryBurst": {
		FieldPath:   "kubelet.registryBurst",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.registryPullQPS": {
		FieldPath:   "kubelet.registryPullQPS",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.serializeImagePulls": {
		FieldPath:   "kubelet.serializeImagePulls",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.streamingConnectionIdleTimeout": {
		FieldPath: "kubelet.streamingConnectionIdleTimeout",
		WriteMode: Mutable,
	},
	"kubelet.systemReserved": {
		FieldPath: "kubelet.systemReserved",
		WriteMode: Immutable,
	},
	"kubelet.topologyManagerPolicy": {
		FieldPath: "kubelet.topologyManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.topologyManagerScope": {
		FieldPath: "kubelet.topologyManagerScope",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig": {
		FieldPath: "machineConfig",
		WriteMode: ServiceSet,
	},
	"machineConfig.allowedKernelArguments": {
		FieldPath:   "machineConfig.allowedKernelArguments",
		WriteMode:   Immutable,
		FeatureGate: "HyperFleetMachineConfig",
	},
	"machineConfig.extensions": {
		FieldPath: "machineConfig.extensions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.files": {
		FieldPath: "machineConfig.files",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.kernelArguments": {
		FieldPath: "machineConfig.kernelArguments",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.kernelType": {
		FieldPath: "machineConfig.kernelType",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.systemdUnits": {
		FieldPath: "machineConfig.systemdUnits",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"maxPods": {
		FieldPath: "maxPods",
		WriteMode: Mutable,
	},
	"memoryThrottlingFactor": {
		FieldPath: "memoryThrottlingFactor",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"network": {
		FieldPath: "network",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"oauth": {
		FieldPath: "oauth",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"podPidsLimit": {
		FieldPath: "podPidsLimit",
		WriteMode: Mutable,
	},
	"proxy": {
		FieldPath: "proxy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"registryBurst": {
		FieldPath:   "registryBurst",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"registryPullQPS": {
		FieldPath:   "registryPullQPS",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"scheduler": {
		FieldPath: "scheduler",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"serializeImagePulls": {
		FieldPath:   "serializeImagePulls",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"spec.accountId": {
		FieldPath: "spec.accountId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.autoRepair": {
		FieldPath: "spec.autoRepair",
		WriteMode: Mutable,
	},
	"spec.creatorARN": {
		FieldPath: "spec.creatorARN",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.deleteProtection": {
		FieldPath: "spec.deleteProtection",
		WriteMode: Mutable,
	},
	"spec.displayName": {
		FieldPath: "spec.displayName",
		WriteMode: Mutable,
	},
	"spec.expirationTimestamp": {
		FieldPath: "spec.expirationTimestamp",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.additionalTrustBundle": {
		FieldPath: "spec.hostedCluster.additionalTrustBundle",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.auditWebhook": {
		FieldPath: "spec.hostedCluster.auditWebhook",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.autoNode": {
		FieldPath: "spec.hostedCluster.autoNode",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.autoscaling": {
		FieldPath: "spec.hostedCluster.autoscaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.capabilities": {
		FieldPath: "spec.hostedCluster.capabilities",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.channel": {
		FieldPath: "spec.hostedCluster.channel",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.clusterID": {
		FieldPath: "spec.hostedCluster.clusterID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration": {
		FieldPath: "spec.hostedCluster.configuration",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.configuration.apiServer": {
		FieldPath: "spec.hostedCluster.configuration.apiServer",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.authentication": {
		FieldPath: "spec.hostedCluster.configuration.authentication",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.featureGate": {
		FieldPath: "spec.hostedCluster.configuration.featureGate",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.image": {
		FieldPath: "spec.hostedCluster.configuration.image",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.ingress": {
		FieldPath: "spec.hostedCluster.configuration.ingress",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet": {
		FieldPath: "spec.hostedCluster.configuration.kubelet",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.configuration.kubelet.allowedUnsafeSysctls": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.allowedUnsafeSysctls",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.containerLogMaxFiles": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.containerLogMaxFiles",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.containerLogMaxSize": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.containerLogMaxSize",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.cpuManagerPolicy": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.cpuManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.cpuManagerPolicyOptions": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.cpuManagerPolicyOptions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.cpuManagerReconcilePeriod": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.cpuManagerReconcilePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.evictionHard": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.evictionHard",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.evictionSoft": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.evictionSoft",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.evictionSoftGracePeriod": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.evictionSoftGracePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.imageGCHighThresholdPercent": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.imageGCHighThresholdPercent",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.imageGCLowThresholdPercent": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.imageGCLowThresholdPercent",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.imageMinimumGCAge": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.imageMinimumGCAge",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.kubeReserved": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.kubeReserved",
		WriteMode: Immutable,
	},
	"spec.hostedCluster.configuration.kubelet.maxPods": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.maxPods",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.memoryThrottlingFactor": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.memoryThrottlingFactor",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.podPidsLimit": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.podPidsLimit",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.registryBurst": {
		FieldPath:   "spec.hostedCluster.configuration.kubelet.registryBurst",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"spec.hostedCluster.configuration.kubelet.registryPullQPS": {
		FieldPath:   "spec.hostedCluster.configuration.kubelet.registryPullQPS",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"spec.hostedCluster.configuration.kubelet.serializeImagePulls": {
		FieldPath:   "spec.hostedCluster.configuration.kubelet.serializeImagePulls",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"spec.hostedCluster.configuration.kubelet.streamingConnectionIdleTimeout": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.streamingConnectionIdleTimeout",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.configuration.kubelet.systemReserved": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.systemReserved",
		WriteMode: Immutable,
	},
	"spec.hostedCluster.configuration.kubelet.topologyManagerPolicy": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.topologyManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.kubelet.topologyManagerScope": {
		FieldPath: "spec.hostedCluster.configuration.kubelet.topologyManagerScope",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.machineConfig": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.configuration.machineConfig.allowedKernelArguments": {
		FieldPath:   "spec.hostedCluster.configuration.machineConfig.allowedKernelArguments",
		WriteMode:   Immutable,
		FeatureGate: "HyperFleetMachineConfig",
	},
	"spec.hostedCluster.configuration.machineConfig.extensions": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig.extensions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.machineConfig.files": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig.files",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.machineConfig.kernelArguments": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig.kernelArguments",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.machineConfig.kernelType": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig.kernelType",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.machineConfig.systemdUnits": {
		FieldPath: "spec.hostedCluster.configuration.machineConfig.systemdUnits",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.network": {
		FieldPath: "spec.hostedCluster.configuration.network",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.oauth": {
		FieldPath: "spec.hostedCluster.configuration.oauth",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.proxy": {
		FieldPath: "spec.hostedCluster.configuration.proxy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration.scheduler": {
		FieldPath: "spec.hostedCluster.configuration.scheduler",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.controlPlaneRelease": {
		FieldPath: "spec.hostedCluster.controlPlaneRelease",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.controllerAvailabilityPolicy": {
		FieldPath: "spec.hostedCluster.controllerAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.dns": {
		FieldPath: "spec.hostedCluster.dns",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.etcd": {
		FieldPath: "spec.hostedCluster.etcd",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.fips": {
		FieldPath: "spec.hostedCluster.fips",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.imageContentSources": {
		FieldPath: "spec.hostedCluster.imageContentSources",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.infraID": {
		FieldPath: "spec.hostedCluster.infraID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.infrastructureAvailabilityPolicy": {
		FieldPath: "spec.hostedCluster.infrastructureAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.issuerURL": {
		FieldPath: "spec.hostedCluster.issuerURL",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.kubeAPIServerDNSName": {
		FieldPath: "spec.hostedCluster.kubeAPIServerDNSName",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.labels": {
		FieldPath: "spec.hostedCluster.labels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.networking": {
		FieldPath: "spec.hostedCluster.networking",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.nodeSelector": {
		FieldPath: "spec.hostedCluster.nodeSelector",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.olmCatalogPlacement": {
		FieldPath: "spec.hostedCluster.olmCatalogPlacement",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.operatorConfiguration": {
		FieldPath: "spec.hostedCluster.operatorConfiguration",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.pausedUntil": {
		FieldPath: "spec.hostedCluster.pausedUntil",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.platform": {
		FieldPath: "spec.hostedCluster.platform",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.pullSecret": {
		FieldPath: "spec.hostedCluster.pullSecret",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.release": {
		FieldPath: "spec.hostedCluster.release",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.secretEncryption": {
		FieldPath: "spec.hostedCluster.secretEncryption",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.serviceAccountSigningKey": {
		FieldPath: "spec.hostedCluster.serviceAccountSigningKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.services": {
		FieldPath: "spec.hostedCluster.services",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.sshKey": {
		FieldPath: "spec.hostedCluster.sshKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.tolerations": {
		FieldPath: "spec.hostedCluster.tolerations",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.updateService": {
		FieldPath: "spec.hostedCluster.updateService",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.internalId": {
		FieldPath: "spec.internalId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.internalPoolId": {
		FieldPath: "spec.internalPoolId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.labels": {
		FieldPath: "spec.labels",
		WriteMode: Mutable,
	},
	"spec.nodePool.arch": {
		FieldPath: "spec.nodePool.arch",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.autoScaling": {
		FieldPath: "spec.nodePool.autoScaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.clusterName": {
		FieldPath: "spec.nodePool.clusterName",
		WriteMode: Mutable,
	},
	"spec.nodePool.config": {
		FieldPath: "spec.nodePool.config",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.management": {
		FieldPath: "spec.nodePool.management",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeDrainTimeout": {
		FieldPath: "spec.nodePool.nodeDrainTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeLabels": {
		FieldPath: "spec.nodePool.nodeLabels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeVolumeDetachTimeout": {
		FieldPath: "spec.nodePool.nodeVolumeDetachTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.osImageStream": {
		FieldPath: "spec.nodePool.osImageStream",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.pausedUntil": {
		FieldPath: "spec.nodePool.pausedUntil",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.platform": {
		FieldPath: "spec.nodePool.platform",
		WriteMode: Mutable,
	},
	"spec.nodePool.release": {
		FieldPath: "spec.nodePool.release",
		WriteMode: Mutable,
	},
	"spec.nodePool.replicas": {
		FieldPath: "spec.nodePool.replicas",
		WriteMode: Mutable,
	},
	"spec.nodePool.taints": {
		FieldPath: "spec.nodePool.taints",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.tuningConfig": {
		FieldPath: "spec.nodePool.tuningConfig",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.properties": {
		FieldPath: "spec.properties",
		WriteMode: Mutable,
	},
	"spec.tags": {
		FieldPath:   "spec.tags",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetAutoScaling",
	},
	"streamingConnectionIdleTimeout": {
		FieldPath: "streamingConnectionIdleTimeout",
		WriteMode: Mutable,
	},
	"systemReserved": {
		FieldPath: "systemReserved",
		WriteMode: Immutable,
	},
	"topologyManagerPolicy": {
		FieldPath: "topologyManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"topologyManagerScope": {
		FieldPath: "topologyManagerScope",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
}
