package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/openshift-online/rosa-hyperfleet-api/clientset/cmd/pathbind-gen/pkg"
	"gopkg.in/yaml.v3"
)

// rootSchemaForOwner maps ownerType to the OpenAPI component schema name.
var rootSchemaForOwner = map[string]string{
	"Cluster":    "Cluster",
	"NodePool":   "NodePool",
	"OidcConfig": "OidcConfig",
}

// runInit reads field_metadata.json (and optionally openapi.yaml) and writes pathbind-draft.yaml.
func runInit(registryPath, openapiPath, outputPath string) error {
	raw, err := os.ReadFile(registryPath)
	if err != nil {
		return fmt.Errorf("reading registry %s: %w", registryPath, err)
	}

	var entries []pkg.RegistryEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return fmt.Errorf("parsing registry: %w", err)
	}

	// Optionally load and parse the OpenAPI schema.
	var oapi *openAPIWalker
	if openapiPath != "" {
		oapi, err = newOpenAPIWalker(openapiPath)
		if err != nil {
			return fmt.Errorf("loading openapi %s: %w", openapiPath, err)
		}
	}

	// Group entries by ownerType; skip service-set and hidden fields.
	byOwner := map[string][]pkg.RegistryEntry{}
	for _, e := range entries {
		if e.WriteMode == "service-set" || e.Hidden {
			continue
		}
		if e.WriteMode != "mutable" && e.WriteMode != "immutable" {
			continue
		}
		byOwner[e.OwnerType] = append(byOwner[e.OwnerType], e)
	}

	draft := pkg.Draft{Resources: map[string]pkg.DraftResource{}}
	for _, owner := range pkg.SortedKeys(byOwner) {
		sdkType, ok := pkg.SDKTypeForOwner[owner]
		if !ok {
			continue
		}
		key := strings.ToLower(owner[:1]) + owner[1:] // Cluster → cluster

		rootSchema := ""
		if oapi != nil {
			rootSchema = rootSchemaForOwner[owner]
		}

		res := pkg.DraftResource{SDKType: sdkType}
		// Deduplicate: a shorter FieldRegistry path may be the parent of a longer one.
		// When OpenAPI expansion is enabled, emit leaves from the shorter path; skip
		// any longer path that is already covered.
		covered := map[string]bool{}

		// metadata.name is required and immutable on every Kubernetes resource.
		// It does not appear in the FieldRegistry (ObjectMeta has no write-mode
		// annotation) but must be in the draft so consumers can bind it.
		covered["metadata.name"] = true
		res.Fields = append(res.Fields, pkg.DraftField{
			Path:       "metadata.name",
			GoType:     "string",
			Operations: []string{"create"},
		})

		// metadata.uid is computed and read-only on every Kubernetes resource.
		// It does not appear in the FieldRegistry (ObjectMeta has no write-mode
		// annotation) but must be in the draft so consumers can use it as a resource ID.
		covered["metadata.uid"] = true
		res.Fields = append(res.Fields, pkg.DraftField{
			Path:       "metadata.uid",
			GoType:     "string",
			Operations: []string{"read"},
		})

		for _, e := range byOwner[owner] {
			ops := []string{"create", "update"}
			if e.WriteMode == "immutable" {
				ops = []string{"create"}
			}

			if oapi != nil && rootSchema != "" {
				// Expand the struct-level FieldRegistry path to its scalar leaves.
				leaves := oapi.expandLeaves(rootSchema, e.FieldPath)
				for _, leaf := range leaves {
					if covered[leaf.path] {
						continue
					}
					covered[leaf.path] = true
					res.Fields = append(res.Fields, pkg.DraftField{
						Path:       leaf.path,
						GoType:     leaf.goType,
						Operations: ops,
					})
				}
			} else {
				// No OpenAPI — emit the struct-level path as-is.
				if !covered[e.FieldPath] {
					covered[e.FieldPath] = true
					res.Fields = append(res.Fields, pkg.DraftField{
						Path:       e.FieldPath,
						Operations: ops,
					})
				}
			}
		}

		// Sort fields by path for deterministic output.
		sort.Slice(res.Fields, func(i, j int) bool {
			return res.Fields[i].Path < res.Fields[j].Path
		})

		draft.Resources[key] = res
	}

	out, err := yaml.Marshal(draft)
	if err != nil {
		return fmt.Errorf("marshaling draft: %w", err)
	}

	//nolint:lll
	header := "# pathbind-draft.yaml — GENERATED by pathbind-gen --mode=init. DO NOT EDIT.\n# Source: field_metadata.json + openapi.yaml\n"

	if err := os.WriteFile(outputPath, append([]byte(header), out...), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}
	fmt.Printf("pathbind-gen: wrote %s\n", outputPath)

	// Report diagnostics from schema resolution.
	if oapi != nil && len(oapi.diagnostics) > 0 {
		for _, diag := range oapi.diagnostics {
			fmt.Printf("pathbind-gen: warning: %s\n", diag)
		}
	}

	return nil
}
