// Code generated by marker-scanner. DO NOT EDIT.

package registry

import (
	"github.com/openshift-online/rosa-hyperfleet-api/hack/api-codegen/pkg/markers"
)

// Type aliases re-exported from markers so that consumers of this package
// do not need to import markers directly.
type WriteMode = markers.WriteMode
type FieldMeta = markers.FieldMeta
type FeatureGateWriteMode = markers.FeatureGateWriteMode

const (
	Mutable    = markers.Mutable
	Immutable  = markers.Immutable
	ServiceSet = markers.ServiceSet
)

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{
	"additionalTrustBundle": {
		FieldPath: "additionalTrustBundle",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"allowedUnsafeSysctls": {
		FieldPath: "allowedUnsafeSysctls",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"apiServer": {
		FieldPath: "apiServer",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"arch": {
		FieldPath: "arch",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"auditWebhook": {
		FieldPath: "auditWebhook",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"authentication": {
		FieldPath: "authentication",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"autoNode": {
		FieldPath: "autoNode",
		WriteMode: ServiceSet,
	},
	"autoScaling": {
		FieldPath: "autoScaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"autoscaling": {
		FieldPath: "autoscaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"capabilities": {
		FieldPath: "capabilities",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"channel": {
		FieldPath: "channel",
		WriteMode: ServiceSet,
	},
	"clusterID": {
		FieldPath: "clusterID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"clusterName": {
		FieldPath: "clusterName",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"config": {
		FieldPath: "config",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"configuration": {
		FieldPath: "configuration",
		WriteMode: ServiceSet,
	},
	"containerLogMaxFiles": {
		FieldPath: "containerLogMaxFiles",
		WriteMode: Mutable,
	},
	"containerLogMaxSize": {
		FieldPath: "containerLogMaxSize",
		WriteMode: Mutable,
	},
	"controlPlaneRelease": {
		FieldPath: "controlPlaneRelease",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"controllerAvailabilityPolicy": {
		FieldPath: "controllerAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"cpuManagerPolicy": {
		FieldPath: "cpuManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"cpuManagerPolicyOptions": {
		FieldPath: "cpuManagerPolicyOptions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"cpuManagerReconcilePeriod": {
		FieldPath: "cpuManagerReconcilePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"dns": {
		FieldPath: "dns",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"etcd": {
		FieldPath: "etcd",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionHard": {
		FieldPath: "evictionHard",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionSoft": {
		FieldPath: "evictionSoft",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"evictionSoftGracePeriod": {
		FieldPath: "evictionSoftGracePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"featureGate": {
		FieldPath: "featureGate",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"fips": {
		FieldPath: "fips",
		WriteMode: ServiceSet,
	},
	"image": {
		FieldPath: "image",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"imageContentSources": {
		FieldPath: "imageContentSources",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"imageGCHighThresholdPercent": {
		FieldPath: "imageGCHighThresholdPercent",
		WriteMode: Mutable,
	},
	"imageGCLowThresholdPercent": {
		FieldPath: "imageGCLowThresholdPercent",
		WriteMode: Mutable,
	},
	"imageMinimumGCAge": {
		FieldPath: "imageMinimumGCAge",
		WriteMode: Mutable,
	},
	"infraID": {
		FieldPath: "infraID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"infrastructureAvailabilityPolicy": {
		FieldPath: "infrastructureAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"ingress": {
		FieldPath: "ingress",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"issuerURL": {
		FieldPath: "issuerURL",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubeAPIServerDNSName": {
		FieldPath: "kubeAPIServerDNSName",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubeReserved": {
		FieldPath: "kubeReserved",
		WriteMode: Immutable,
	},
	"kubelet": {
		FieldPath: "kubelet",
		WriteMode: ServiceSet,
	},
	"kubelet.allowedUnsafeSysctls": {
		FieldPath: "kubelet.allowedUnsafeSysctls",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.containerLogMaxFiles": {
		FieldPath: "kubelet.containerLogMaxFiles",
		WriteMode: Mutable,
	},
	"kubelet.containerLogMaxSize": {
		FieldPath: "kubelet.containerLogMaxSize",
		WriteMode: Mutable,
	},
	"kubelet.cpuManagerPolicy": {
		FieldPath: "kubelet.cpuManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.cpuManagerPolicyOptions": {
		FieldPath: "kubelet.cpuManagerPolicyOptions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.cpuManagerReconcilePeriod": {
		FieldPath: "kubelet.cpuManagerReconcilePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionHard": {
		FieldPath: "kubelet.evictionHard",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionSoft": {
		FieldPath: "kubelet.evictionSoft",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.evictionSoftGracePeriod": {
		FieldPath: "kubelet.evictionSoftGracePeriod",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.imageGCHighThresholdPercent": {
		FieldPath: "kubelet.imageGCHighThresholdPercent",
		WriteMode: Mutable,
	},
	"kubelet.imageGCLowThresholdPercent": {
		FieldPath: "kubelet.imageGCLowThresholdPercent",
		WriteMode: Mutable,
	},
	"kubelet.imageMinimumGCAge": {
		FieldPath: "kubelet.imageMinimumGCAge",
		WriteMode: Mutable,
	},
	"kubelet.kubeReserved": {
		FieldPath: "kubelet.kubeReserved",
		WriteMode: Immutable,
	},
	"kubelet.maxPods": {
		FieldPath: "kubelet.maxPods",
		WriteMode: Mutable,
	},
	"kubelet.memoryThrottlingFactor": {
		FieldPath: "kubelet.memoryThrottlingFactor",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.podPidsLimit": {
		FieldPath: "kubelet.podPidsLimit",
		WriteMode: Mutable,
	},
	"kubelet.registryBurst": {
		FieldPath:   "kubelet.registryBurst",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.registryPullQPS": {
		FieldPath:   "kubelet.registryPullQPS",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.serializeImagePulls": {
		FieldPath:   "kubelet.serializeImagePulls",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"kubelet.streamingConnectionIdleTimeout": {
		FieldPath: "kubelet.streamingConnectionIdleTimeout",
		WriteMode: Mutable,
	},
	"kubelet.systemReserved": {
		FieldPath: "kubelet.systemReserved",
		WriteMode: Immutable,
	},
	"kubelet.topologyManagerPolicy": {
		FieldPath: "kubelet.topologyManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"kubelet.topologyManagerScope": {
		FieldPath: "kubelet.topologyManagerScope",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"labels": {
		FieldPath: "labels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig": {
		FieldPath: "machineConfig",
		WriteMode: ServiceSet,
	},
	"machineConfig.allowedKernelArguments": {
		FieldPath:   "machineConfig.allowedKernelArguments",
		WriteMode:   Immutable,
		FeatureGate: "HyperFleetMachineConfig",
	},
	"machineConfig.extensions": {
		FieldPath: "machineConfig.extensions",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.files": {
		FieldPath: "machineConfig.files",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.fips": {
		FieldPath: "machineConfig.fips",
		WriteMode: Immutable,
	},
	"machineConfig.kernelArguments": {
		FieldPath: "machineConfig.kernelArguments",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.kernelType": {
		FieldPath: "machineConfig.kernelType",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"machineConfig.systemdUnits": {
		FieldPath: "machineConfig.systemdUnits",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"management": {
		FieldPath: "management",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"maxPods": {
		FieldPath: "maxPods",
		WriteMode: Mutable,
	},
	"memoryThrottlingFactor": {
		FieldPath: "memoryThrottlingFactor",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"network": {
		FieldPath: "network",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"networking": {
		FieldPath: "networking",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"nodeDrainTimeout": {
		FieldPath: "nodeDrainTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"nodeLabels": {
		FieldPath: "nodeLabels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"nodeSelector": {
		FieldPath: "nodeSelector",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"nodeVolumeDetachTimeout": {
		FieldPath: "nodeVolumeDetachTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"oauth": {
		FieldPath: "oauth",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"olmCatalogPlacement": {
		FieldPath: "olmCatalogPlacement",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"operatorConfiguration": {
		FieldPath: "operatorConfiguration",
		WriteMode: ServiceSet,
	},
	"osImageStream": {
		FieldPath: "osImageStream",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"pausedUntil": {
		FieldPath: "pausedUntil",
		WriteMode: ServiceSet,
	},
	"platform": {
		FieldPath: "platform",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"podPidsLimit": {
		FieldPath: "podPidsLimit",
		WriteMode: Mutable,
	},
	"proxy": {
		FieldPath: "proxy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"pullSecret": {
		FieldPath: "pullSecret",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"registryBurst": {
		FieldPath:   "registryBurst",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"registryPullQPS": {
		FieldPath:   "registryPullQPS",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"release": {
		FieldPath: "release",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"replicas": {
		FieldPath: "replicas",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"scheduler": {
		FieldPath: "scheduler",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"secretEncryption": {
		FieldPath: "secretEncryption",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"serializeImagePulls": {
		FieldPath:   "serializeImagePulls",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetKubeletAdvanced",
	},
	"serviceAccountSigningKey": {
		FieldPath: "serviceAccountSigningKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"services": {
		FieldPath: "services",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.accountId": {
		FieldPath: "spec.accountId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.autoRepair": {
		FieldPath: "spec.autoRepair",
		WriteMode: Mutable,
	},
	"spec.creatorARN": {
		FieldPath: "spec.creatorARN",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.deleteProtection": {
		FieldPath: "spec.deleteProtection",
		WriteMode: Mutable,
	},
	"spec.displayName": {
		FieldPath: "spec.displayName",
		WriteMode: Mutable,
	},
	"spec.expirationTimestamp": {
		FieldPath: "spec.expirationTimestamp",
		WriteMode: Mutable,
	},
	"spec.internalId": {
		FieldPath: "spec.internalId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.internalPoolId": {
		FieldPath: "spec.internalPoolId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.labels": {
		FieldPath: "spec.labels",
		WriteMode: Mutable,
	},
	"spec.properties": {
		FieldPath: "spec.properties",
		WriteMode: Mutable,
	},
	"spec.tags": {
		FieldPath:   "spec.tags",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetAutoScaling",
	},
	"sshKey": {
		FieldPath: "sshKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"streamingConnectionIdleTimeout": {
		FieldPath: "streamingConnectionIdleTimeout",
		WriteMode: Mutable,
	},
	"systemReserved": {
		FieldPath: "systemReserved",
		WriteMode: Immutable,
	},
	"taints": {
		FieldPath: "taints",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"tolerations": {
		FieldPath: "tolerations",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"topologyManagerPolicy": {
		FieldPath: "topologyManagerPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"topologyManagerScope": {
		FieldPath: "topologyManagerScope",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"tuningConfig": {
		FieldPath: "tuningConfig",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"updateService": {
		FieldPath: "updateService",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
}
