// Code generated by marker-scanner. DO NOT EDIT.

package registry

// WriteMode defines how a field can be mutated by customers
type WriteMode string

const (
	// Mutable fields can be set on create and changed on update
	Mutable WriteMode = "mutable"

	// Immutable fields can be set on create but cannot be changed on update
	Immutable WriteMode = "immutable"

	// ServiceSet fields are set by the platform and cannot be set by customers
	ServiceSet WriteMode = "service-set"
)

// FeatureGateWriteMode represents a write-mode override for a specific feature gate
type FeatureGateWriteMode struct {
	// FeatureGate is the gate that enables this write-mode (empty string = default/no gates enabled)
	FeatureGate string

	// WriteMode is the effective write-mode when this gate condition matches
	WriteMode WriteMode
}

// FieldMeta contains metadata for a single field
type FieldMeta struct {
	// FieldPath is the JSON path to the field (e.g., "spec.name")
	FieldPath string

	// WriteMode controls customer mutability
	WriteMode WriteMode

	// FeatureGate is the gate required to use this field (empty if no gate required)
	FeatureGate string

	// Hidden indicates if the field is excluded from OpenAPI
	Hidden bool

	// FeatureGateAwareWriteModes allows write-mode to vary based on enabled feature gates
	FeatureGateAwareWriteModes []FeatureGateWriteMode
}

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{
	"spec.accountId": {
		FieldPath: "spec.accountId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.autoRepair": {
		FieldPath: "spec.autoRepair",
		WriteMode: Mutable,
	},
	"spec.creatorARN": {
		FieldPath: "spec.creatorARN",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.deleteProtection": {
		FieldPath: "spec.deleteProtection",
		WriteMode: Mutable,
	},
	"spec.displayName": {
		FieldPath: "spec.displayName",
		WriteMode: Mutable,
	},
	"spec.expirationTimestamp": {
		FieldPath: "spec.expirationTimestamp",
		WriteMode: Mutable,
	},
	"spec.hostedCluster.additionalTrustBundle": {
		FieldPath: "spec.hostedCluster.additionalTrustBundle",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.auditWebhook": {
		FieldPath: "spec.hostedCluster.auditWebhook",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.autoNode": {
		FieldPath: "spec.hostedCluster.autoNode",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.autoscaling": {
		FieldPath: "spec.hostedCluster.autoscaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.capabilities": {
		FieldPath: "spec.hostedCluster.capabilities",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.channel": {
		FieldPath: "spec.hostedCluster.channel",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.clusterID": {
		FieldPath: "spec.hostedCluster.clusterID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.configuration": {
		FieldPath: "spec.hostedCluster.configuration",
		WriteMode: ServiceSet,
	},
	"spec.hostedCluster.controlPlaneRelease": {
		FieldPath: "spec.hostedCluster.controlPlaneRelease",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.controllerAvailabilityPolicy": {
		FieldPath: "spec.hostedCluster.controllerAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.dns": {
		FieldPath: "spec.hostedCluster.dns",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.etcd": {
		FieldPath: "spec.hostedCluster.etcd",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.fips": {
		FieldPath: "spec.hostedCluster.fips",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.imageContentSources": {
		FieldPath: "spec.hostedCluster.imageContentSources",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.infraID": {
		FieldPath: "spec.hostedCluster.infraID",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.infrastructureAvailabilityPolicy": {
		FieldPath: "spec.hostedCluster.infrastructureAvailabilityPolicy",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.issuerURL": {
		FieldPath: "spec.hostedCluster.issuerURL",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.kubeAPIServerDNSName": {
		FieldPath: "spec.hostedCluster.kubeAPIServerDNSName",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.labels": {
		FieldPath: "spec.hostedCluster.labels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.networking": {
		FieldPath: "spec.hostedCluster.networking",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.nodeSelector": {
		FieldPath: "spec.hostedCluster.nodeSelector",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.olmCatalogPlacement": {
		FieldPath: "spec.hostedCluster.olmCatalogPlacement",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.operatorConfiguration": {
		FieldPath: "spec.hostedCluster.operatorConfiguration",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.pausedUntil": {
		FieldPath: "spec.hostedCluster.pausedUntil",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.platform": {
		FieldPath: "spec.hostedCluster.platform",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.pullSecret": {
		FieldPath: "spec.hostedCluster.pullSecret",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.release": {
		FieldPath: "spec.hostedCluster.release",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.secretEncryption": {
		FieldPath: "spec.hostedCluster.secretEncryption",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.serviceAccountSigningKey": {
		FieldPath: "spec.hostedCluster.serviceAccountSigningKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.services": {
		FieldPath: "spec.hostedCluster.services",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.sshKey": {
		FieldPath: "spec.hostedCluster.sshKey",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.tolerations": {
		FieldPath: "spec.hostedCluster.tolerations",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.hostedCluster.updateService": {
		FieldPath: "spec.hostedCluster.updateService",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.internalId": {
		FieldPath: "spec.internalId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.internalPoolId": {
		FieldPath: "spec.internalPoolId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.labels": {
		FieldPath: "spec.labels",
		WriteMode: Mutable,
	},
	"spec.nodePool.arch": {
		FieldPath: "spec.nodePool.arch",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.autoScaling": {
		FieldPath: "spec.nodePool.autoScaling",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.clusterName": {
		FieldPath: "spec.nodePool.clusterName",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.config": {
		FieldPath: "spec.nodePool.config",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.management": {
		FieldPath: "spec.nodePool.management",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeDrainTimeout": {
		FieldPath: "spec.nodePool.nodeDrainTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeLabels": {
		FieldPath: "spec.nodePool.nodeLabels",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.nodeVolumeDetachTimeout": {
		FieldPath: "spec.nodePool.nodeVolumeDetachTimeout",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.pausedUntil": {
		FieldPath: "spec.nodePool.pausedUntil",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.platform": {
		FieldPath: "spec.nodePool.platform",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.release": {
		FieldPath: "spec.nodePool.release",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.replicas": {
		FieldPath: "spec.nodePool.replicas",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.taints": {
		FieldPath: "spec.nodePool.taints",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.nodePool.tuningConfig": {
		FieldPath: "spec.nodePool.tuningConfig",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"spec.properties": {
		FieldPath: "spec.properties",
		WriteMode: Mutable,
	},
	"spec.tags": {
		FieldPath:   "spec.tags",
		WriteMode:   Mutable,
		FeatureGate: "HyperFleetAutoScaling",
	},
}
