// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectDNSReservation converts CRD DNSReservation to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectDNSReservation(crd *v1alpha1.DNSReservation) *rest.DNSReservation {
	if crd == nil {
		return nil
	}

	spec := projectDNSReservationSpec(crd.Spec)
	status := projectDNSReservationStatus(crd.Status)
	return &rest.DNSReservation{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectDNSReservationSpec(crd v1alpha1.DNSReservationSpec) rest.DNSReservationSpec {
	data, _ := json.Marshal(crd)
	var out rest.DNSReservationSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectDNSReservationStatus(crd v1alpha1.DNSReservationStatus) rest.DNSReservationStatus {
	data, _ := json.Marshal(crd)
	var out rest.DNSReservationStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectDNSReservation converts REST DNSReservationSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectDNSReservation(spec *rest.DNSReservationSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.DNSReservationSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.DNSReservationSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
