// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectManagementCluster converts CRD ManagementCluster to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectManagementCluster(crd *v1alpha1.ManagementCluster) *rest.ManagementCluster {
	if crd == nil {
		return nil
	}

	spec := projectManagementClusterSpec(crd.Spec)
	status := projectManagementClusterStatus(crd.Status)
	return &rest.ManagementCluster{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectManagementClusterSpec(crd v1alpha1.ManagementClusterSpec) rest.ManagementClusterSpec {
	data, _ := json.Marshal(crd)
	var out rest.ManagementClusterSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectManagementClusterStatus(crd v1alpha1.ManagementClusterStatus) rest.ManagementClusterStatus {
	data, _ := json.Marshal(crd)
	var out rest.ManagementClusterStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectManagementCluster converts REST ManagementClusterSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectManagementCluster(spec *rest.ManagementClusterSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.ManagementClusterSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.ManagementClusterSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
