// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectManifest converts CRD Manifest to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectManifest(crd *v1alpha1.Manifest) *rest.Manifest {
	if crd == nil {
		return nil
	}

	spec := projectManifestSpec(crd.Spec)
	status := projectManifestStatus(crd.Status)
	return &rest.Manifest{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectManifestSpec(crd v1alpha1.ManifestSpec) rest.ManifestSpec {
	data, _ := json.Marshal(crd)
	var out rest.ManifestSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectManifestStatus(crd v1alpha1.ManifestStatus) rest.ManifestStatus {
	data, _ := json.Marshal(crd)
	var out rest.ManifestStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectManifest converts REST ManifestSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectManifest(spec *rest.ManifestSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.ManifestSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.ManifestSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
