// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectNodePool converts CRD NodePool to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectNodePool(crd *v1alpha1.NodePool) *rest.NodePool {
	if crd == nil {
		return nil
	}

	spec := projectNodePoolSpec(crd.Spec)
	status := projectNodePoolStatus(crd.Status)
	return &rest.NodePool{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectNodePoolSpec(crd v1alpha1.NodePoolSpec) rest.NodePoolSpec {
	data, _ := json.Marshal(crd)
	var out rest.NodePoolSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectNodePoolStatus(crd v1alpha1.NodePoolStatus) rest.NodePoolStatus {
	data, _ := json.Marshal(crd)
	var out rest.NodePoolStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectNodePool converts REST NodePoolSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectNodePool(spec *rest.NodePoolSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.NodePoolSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.NodePoolSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
