// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectOidcConfig converts CRD OidcConfig to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectOidcConfig(crd *v1alpha1.OidcConfig) *rest.OidcConfig {
	if crd == nil {
		return nil
	}

	spec := projectOidcConfigSpec(crd.Spec)
	status := projectOidcConfigStatus(crd.Status)
	return &rest.OidcConfig{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectOidcConfigSpec(crd v1alpha1.OidcConfigSpec) rest.OidcConfigSpec {
	data, _ := json.Marshal(crd)
	var out rest.OidcConfigSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectOidcConfigStatus(crd v1alpha1.OidcConfigStatus) rest.OidcConfigStatus {
	data, _ := json.Marshal(crd)
	var out rest.OidcConfigStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectOidcConfig converts REST OidcConfigSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectOidcConfig(spec *rest.OidcConfigSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.OidcConfigSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.OidcConfigSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
