// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"

	v1alpha1 "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1"
	rest "github.com/openshift-online/rosa-hyperfleet-api/api/v1alpha1/public"
	"github.com/openshift-online/rosa-hyperfleet-api/platform-api/pkg/conversion"
)

// ProjectPlacement converts CRD Placement to REST (visible fields only).
// Uses JSON roundtrip: marshal CRD → unmarshal into REST, so hidden fields are
// automatically dropped (REST types lack them).
func ProjectPlacement(crd *v1alpha1.Placement) *rest.Placement {
	if crd == nil {
		return nil
	}

	spec := projectPlacementSpec(crd.Spec)
	status := projectPlacementStatus(crd.Status)
	return &rest.Placement{
		TypeMeta:   crd.TypeMeta,
		ObjectMeta: crd.ObjectMeta,
		Spec:       spec,
		Status:     status,
	}
}

func projectPlacementSpec(crd v1alpha1.PlacementSpec) rest.PlacementSpec {
	data, _ := json.Marshal(crd)
	var out rest.PlacementSpec
	_ = json.Unmarshal(data, &out)
	return out
}

func projectPlacementStatus(crd v1alpha1.PlacementStatus) rest.PlacementStatus {
	data, _ := json.Marshal(crd)
	var out rest.PlacementStatus
	_ = json.Unmarshal(data, &out)
	return out
}

// UnprojectPlacement converts REST PlacementSpec to CRD with service-set enrichment.
// Uses JSON roundtrip: marshal REST → unmarshal into CRD, then overlay service-set fields.
func UnprojectPlacement(spec *rest.PlacementSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.PlacementSpec {
	if spec == nil {
		return nil
	}

	data, _ := json.Marshal(spec)
	var crdSpec v1alpha1.PlacementSpec
	_ = json.Unmarshal(data, &crdSpec)

	if enrichment != nil {
		ssData, _ := json.Marshal(enrichment)
		_ = json.Unmarshal(ssData, &crdSpec)
	}

	return &crdSpec
}
