/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// bridge-gen reads +bridge:* markers from Go source files and emits generated Go code.
//
// Modes:
//
//	--mode=bridge (default): emits bridge_mappings_generated.go containing a
//	  per-type FieldMapping map derived from +bridge:field markers.
//
//	--mode=platform: emits bridge_wrappers_generated.go containing wrapper types
//	  for resources annotated with +bridge:watch=disabled and/or +bridge:wait.
//	  The Watch method returns ErrWatchNotSupported; WaitUntil provides
//	  polling-based synchronization via a caller-supplied condition function.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
)

var (
	bridgeMarkerRE  = regexp.MustCompile(`\+bridge:field=([^,\s]+),meta=([^\s]+)`)
	watchDisabledRE = regexp.MustCompile(`\+bridge:watch=disabled`)
	waitRE          = regexp.MustCompile(`\+bridge:wait\b`)
	nonNamespacedRE = regexp.MustCompile(`\+genclient:nonNamespaced\b`)
)

// fieldMapping holds a single wire→metadata field translation.
type fieldMapping struct {
	Bridge string
	Meta   string
}

// resourceType describes a CRD type annotated with +bridge:watch or +bridge:wait.
type resourceType struct {
	Name          string // e.g. "Cluster"
	PluralName    string // e.g. "Clusters"
	PluralLower   string // e.g. "clusters" — URL path segment key
	LowerName     string // e.g. "cluster"
	WatchDisabled bool
	Wait          bool
	NonNamespaced bool           // set when +genclient:nonNamespaced is present
	Mappings      []fieldMapping // from +bridge:field markers on this type
}

// ── Templates ────────────────────────────────────────────────────────────────

const mappingsTmpl = `// Code generated by bridge-gen. DO NOT EDIT.

package {{.Package}}

// defaultMappings maps platform-api wire-format field names to Kubernetes
// metadata field names, keyed by the lowercase plural resource name that
// matches the URL path segment (e.g. "clusters", "nodepools").
// Generated from +bridge:field markers on CRD types.
var defaultMappings = map[string][]FieldMapping{
{{- range .Types}}{{if .Mappings}}
	"{{.PluralLower}}": {
	{{- range .Mappings}}
		{Bridge: "{{.Bridge}}", Meta: "{{.Meta}}"},
	{{- end}}
	},
{{- end}}{{end}}
}
`

const platformTmpl = `// Code generated by bridge-gen. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"fmt"
	"strconv"
{{if .AnyWait}}	"time"
{{end}}
{{if .AnyWait}}	k8serrors "k8s.io/apimachinery/pkg/api/errors"
{{end}}	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/rest"

	v1alpha1 "{{.ApiPkgImport}}"
	typedclient "{{.TypedPkgImport}}"
)
{{range .Types}}
// {{.Name}}Interface is the platform-scoped client for {{.Name}} resources.
// Only operations and options supported by the Hyperfleet platform API are exposed.
// Watch is intentionally absent — the platform API does not support the Kubernetes
// watch stream protocol; use WaitUntil for polling-based synchronization instead.
type {{.Name}}Interface interface {
	Create(ctx context.Context, obj *v1alpha1.{{.Name}}, opts CreateOptions) (*v1alpha1.{{.Name}}, error)
	Update(ctx context.Context, obj *v1alpha1.{{.Name}}, opts UpdateOptions) (*v1alpha1.{{.Name}}, error)
	Delete(ctx context.Context, name string, opts DeleteOptions) error
	Get(ctx context.Context, name string, opts GetOptions) (*v1alpha1.{{.Name}}, error)
	List(ctx context.Context, opts ListOptions) (*v1alpha1.{{.Name}}List, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts PatchOptions) (*v1alpha1.{{.Name}}, error)
{{- if .Wait}}
	// WaitUntil polls until condition(obj) returns true, the resource is absent
	// (condition is called with nil), or the timeout elapses.
	WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.{{.Name}}) bool, interval, timeout time.Duration) error
{{- end}}
}

type {{.LowerName}}Client struct {
{{- if .NonNamespaced}}
	inner typedclient.{{.Name}}Interface
{{- else}}
	inner     typedclient.{{.Name}}Interface
	namespace string // parent namespace passed to {{.PluralName}}(namespace)
{{- end}}
}

func (c *{{.LowerName}}Client) Create(ctx context.Context, obj *v1alpha1.{{.Name}}, opts CreateOptions) (*v1alpha1.{{.Name}}, error) {
{{- if .NonNamespaced}}{{else}}
	// Always enforce the client namespace in the body so the handler can derive the
	// parent resource ID. The SigV4 transport strips /namespaces/{value}/ from the
	// URL before it reaches the server, making the body the only carrier.
	// A caller-supplied namespace that differs from the client namespace is replaced
	// rather than silently passed through.
	if c.namespace != "" && obj.Namespace != c.namespace {
		routed := obj.DeepCopy()
		routed.Namespace = c.namespace
		return c.inner.Create(ctx, routed, metav1.CreateOptions{})
	}
{{- end}}
	return c.inner.Create(ctx, obj, metav1.CreateOptions{})
}

func (c *{{.LowerName}}Client) Get(ctx context.Context, name string, opts GetOptions) (*v1alpha1.{{.Name}}, error) {
	return c.inner.Get(ctx, name, metav1.GetOptions{})
}

func (c *{{.LowerName}}Client) List(ctx context.Context, opts ListOptions) (*v1alpha1.{{.Name}}List, error) {
	if opts.Limit < 0 || opts.Limit > 100 {
		return nil, fmt.Errorf("List: Limit must be between 0 and 100, got %d", opts.Limit)
	}
	if opts.Offset < 0 {
		return nil, fmt.Errorf("List: Offset must be non-negative, got %d", opts.Offset)
	}
	mo := metav1.ListOptions{Limit: opts.Limit}
	if opts.Offset > 0 {
		mo.Continue = strconv.FormatInt(opts.Offset, 10)
	}
	return c.inner.List(ctx, mo)
}

func (c *{{.LowerName}}Client) Update(ctx context.Context, obj *v1alpha1.{{.Name}}, opts UpdateOptions) (*v1alpha1.{{.Name}}, error) {
	// The generated client builds the PUT URL using obj.Name (the human-readable
	// name), but the platform API routes mutations by UID. Setting Name to the
	// UID on a deep copy ensures the URL is correct without mutating the caller's
	// object. The name field sent in the request body is ignored by the server —
	// the update DTO only binds "spec", so the JSON decoder discards everything
	// else, including any name/id fields.
	routed := obj.DeepCopy()
	routed.Name = string(obj.UID)
	return c.inner.Update(ctx, routed, metav1.UpdateOptions{})
}

func (c *{{.LowerName}}Client) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts PatchOptions) (*v1alpha1.{{.Name}}, error) {
	return c.inner.Patch(ctx, name, pt, data, metav1.PatchOptions{})
}

func (c *{{.LowerName}}Client) Delete(ctx context.Context, name string, opts DeleteOptions) error {
	return c.inner.Delete(ctx, name, metav1.DeleteOptions{})
}
{{if .Wait}}
func (c *{{.LowerName}}Client) WaitUntil(ctx context.Context, id string, condition func(*v1alpha1.{{.Name}}) bool, interval, timeout time.Duration) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	poll := func() (bool, error) {
		obj, err := c.inner.Get(ctx, id, metav1.GetOptions{})
		if err != nil {
			if k8serrors.IsNotFound(err) {
				return condition(nil), nil
			}
			// Transient server-side errors are retried; only client errors are fatal.
			if k8serrors.IsServiceUnavailable(err) || k8serrors.IsServerTimeout(err) || k8serrors.IsInternalError(err) {
				return false, nil
			}
			return false, err
		}
		return condition(obj), nil
	}
	if interval <= 0 {
		return fmt.Errorf("WaitUntil: interval must be positive, got %v", interval)
	}
	if done, err := poll(); err != nil || done {
		return err
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			if done, err := poll(); err != nil || done {
				return err
			}
		}
	}
}
{{- end}}
{{end}}
// {{.TypedClientPrefix}}Interface is the platform-scoped typed client for the hyperfleet.io/v1alpha1 group.
type {{.TypedClientPrefix}}Interface interface {
	RESTClient() rest.Interface
{{- range .Types}}
{{- if .NonNamespaced}}
	{{.PluralName}}() {{.Name}}Interface
{{- else}}
	{{.PluralName}}(namespace string) {{.Name}}Interface
{{- end}}
{{- end}}
}

type wrappedV1alpha1 struct {
	inner typedclient.{{.TypedClientPrefix}}Interface
}

// New{{.TypedClientPrefix}}Client wraps the generated typed client with platform-specific interfaces.
func New{{.TypedClientPrefix}}Client(inner typedclient.{{.TypedClientPrefix}}Interface) {{.TypedClientPrefix}}Interface {
	return &wrappedV1alpha1{inner: inner}
}

func (w *wrappedV1alpha1) RESTClient() rest.Interface {
	return w.inner.RESTClient()
}
{{range .Types}}
{{- if .NonNamespaced}}
func (w *wrappedV1alpha1) {{.PluralName}}() {{.Name}}Interface {
	return &{{.LowerName}}Client{inner: w.inner.{{.PluralName}}()}
}
{{- else}}
func (w *wrappedV1alpha1) {{.PluralName}}(namespace string) {{.Name}}Interface {
	return &{{.LowerName}}Client{inner: w.inner.{{.PluralName}}(namespace), namespace: namespace}
}
{{- end}}
{{end}}`

// ── main ─────────────────────────────────────────────────────────────────────

func main() {
	mode := flag.String("mode", "bridge", "generation mode: bridge or platform")
	inputDir := flag.String("input-dir", "", "directory of Go source files to scan for +bridge:* markers")
	outputDir := flag.String("output-dir", "", "directory to write the generated file")
	outputPkg := flag.String("output-pkg", "transport", "Go package name for the generated file")
	headerFile := flag.String("go-header-file", "", "file whose contents are prepended to the generated output")
	typedPkg := flag.String("typed-pkg-import", "", "[platform] import path of the generated typed client package")
	apiPkg := flag.String("api-pkg-import", "", "[platform] import path of the CRD API types package")
	typedClientPrefix := flag.String("typed-client-prefix", "V1alpha1", "[platform] group-level interface name prefix (e.g. V1alpha1 or V1alpha1Public)")
	flag.Parse()

	if *inputDir == "" || *outputDir == "" {
		fmt.Fprintln(os.Stderr, "bridge-gen: --input-dir and --output-dir are required")
		os.Exit(1)
	}

	header := readHeader(*headerFile)

	if err := os.MkdirAll(*outputDir, 0o755); err != nil {
		fatalf("creating output dir: %v", err)
	}

	switch *mode {
	case "bridge":
		generateMappings(*inputDir, *outputDir, *outputPkg, header)
	case "platform":
		if *typedPkg == "" || *apiPkg == "" {
			fmt.Fprintln(os.Stderr, "bridge-gen: platform mode requires --typed-pkg-import and --api-pkg-import")
			os.Exit(1)
		}
		generatePlatform(*inputDir, *outputDir, *outputPkg, *typedPkg, *apiPkg, *typedClientPrefix, header)
	default:
		fatalf("unknown mode %q; use bridge or platform", *mode)
	}
}

// ── bridge mode ─────────────────────────────────────────────────────────────

func generateMappings(inputDir, outputDir, pkg, header string) {
	types := collectResourceTypes(inputDir)

	outPath := filepath.Join(outputDir, "bridge_mappings_generated.go")
	f, err := os.Create(outPath)
	if err != nil {
		fatalf("creating %s: %v", outPath, err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fatalf("closing %s: %v", outPath, err)
		}
		fmt.Printf("bridge-gen: wrote %s\n", outPath)
	}()

	if _, err := fmt.Fprint(f, header); err != nil {
		fatalf("writing header to %s: %v", outPath, err)
	}

	tmpl := template.Must(template.New("bridge").Parse(mappingsTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package": pkg,
		"Types":   types,
	}); err != nil {
		fatalf("rendering template: %v", err)
	}
}

// ── platform mode ─────────────────────────────────────────────────────────────

func generatePlatform(inputDir, outputDir, pkg, typedPkgImport, apiPkgImport, typedClientPrefix, header string) {
	types := collectResourceTypes(inputDir)
	if len(types) == 0 {
		fatalf("no resource types with +bridge:watch or +bridge:wait markers found in %s", inputDir)
	}

	outPath := filepath.Join(outputDir, "bridge_wrappers_generated.go")
	f, err := os.Create(outPath)
	if err != nil {
		fatalf("creating %s: %v", outPath, err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fatalf("closing %s: %v", outPath, err)
		}
		fmt.Printf("bridge-gen: wrote %s\n", outPath)
	}()

	if _, err := fmt.Fprint(f, header); err != nil {
		fatalf("writing header to %s: %v", outPath, err)
	}

	anyWait, anyWatchDisabled := false, false
	for _, t := range types {
		if t.Wait {
			anyWait = true
		}
		if t.WatchDisabled {
			anyWatchDisabled = true
		}
	}

	tmpl := template.Must(template.New("platform").Parse(platformTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package":           pkg,
		"ApiPkgImport":      apiPkgImport,
		"TypedPkgImport":    typedPkgImport,
		"TypedClientPrefix": typedClientPrefix,
		"Types":             types,
		"AnyWait":           anyWait,
		"AnyWatchDisabled":  anyWatchDisabled,
	}); err != nil {
		fatalf("rendering template: %v", err)
	}
}

// collectResourceTypes scans all Go source files in dir for type declarations
// annotated with +bridge:watch=disabled and/or +bridge:wait.
//
// Because generators conventionally place markers in a floating comment block
// (separated by a blank line from the actual doc comment), markers are found by
// scanning all comment groups and associating each group with the nearest type
// declaration that follows it in the file.
func collectResourceTypes(dir string) []resourceType {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		fatalf("parsing %s: %v", dir, err)
	}

	seen := map[string]bool{}
	var types []resourceType

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			// Collect all type declarations with their source positions.
			type typePos struct {
				name string
				pos  token.Pos
			}
			var typeDecls []typePos
			for _, decl := range file.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					typeDecls = append(typeDecls, typePos{name: ts.Name.Name, pos: gd.Pos()})
				}
			}
			sort.Slice(typeDecls, func(i, j int) bool { return typeDecls[i].pos < typeDecls[j].pos })

			// For each comment group containing watch/wait markers, find the
			// next type declaration that follows it.
			for _, cg := range file.Comments {
				var hasWatch, hasWait, hasNonNamespaced bool
				var typeMappings []fieldMapping
				seenMappings := map[string]bool{}
				for _, c := range cg.List {
					if watchDisabledRE.MatchString(c.Text) {
						hasWatch = true
					}
					if waitRE.MatchString(c.Text) {
						hasWait = true
					}
					if nonNamespacedRE.MatchString(c.Text) {
						hasNonNamespaced = true
					}
					for _, m := range bridgeMarkerRE.FindAllStringSubmatch(c.Text, -1) {
						key := m[1] + ":" + m[2]
						if !seenMappings[key] {
							seenMappings[key] = true
							typeMappings = append(typeMappings, fieldMapping{Bridge: m[1], Meta: m[2]})
						}
					}
				}
				if !hasWatch && !hasWait {
					continue
				}
				sort.Slice(typeMappings, func(i, j int) bool { return typeMappings[i].Bridge < typeMappings[j].Bridge })

				cgEnd := cg.End()
				for _, td := range typeDecls {
					if td.pos <= cgEnd {
						continue
					}
					if seen[td.name] {
						continue
					}
					seen[td.name] = true
					name := td.name
					plural := name + "s"
					types = append(types, resourceType{
						Name:          name,
						PluralName:    plural,
						PluralLower:   strings.ToLower(plural),
						LowerName:     strings.ToLower(name[:1]) + name[1:],
						WatchDisabled: hasWatch,
						Wait:          hasWait,
						NonNamespaced: hasNonNamespaced,
						Mappings:      typeMappings,
					})
					break
				}
			}
		}
	}

	sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })
	return types
}

// ── helpers ───────────────────────────────────────────────────────────────────

func readHeader(path string) string {
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		fatalf("reading header file: %v", err)
	}
	return strings.ReplaceAll(string(b), "YEAR", strconv.Itoa(time.Now().Year()))
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "bridge-gen: "+format+"\n", args...)
	os.Exit(1)
}
